Update dockerfile to use a newer version of Node
When I tried to run example1, it failed in runtime with the following error:
/usr/local/lib/node_modules/redis-commander/bin/redis-commander.js:5
let optimist = require('optimist');
^^^
SyntaxError: Unexpected strict mode reserved word
at exports.runInThisContext (vm.js:73:16)
at Module._compile (module.js:443:25)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
at node.js:814:3

Changing the node version to a newer version like 11.9.0 worked.